/** Central re-export of the lucide-react icons used across the app, so
 * every page pulls icons from one place and stays visually consistent. */
export {
  LayoutDashboard as OverviewIcon,
  FileStack as RegulationsIcon,
  ListChecks as RulesIcon,
  Network as GraphIcon,
  CheckCircle2 as DecisionsIcon,
  GitBranch as ImpactIcon,
  SlidersHorizontal as SimulatorIcon,
  FlaskConical as EvaluationIcon,
  LayoutDashboard,
  FileStack,
  ListChecks,
  Network,
  CheckCircle2,
  GitBranch,
  SlidersHorizontal,
  FlaskConical,
  ChevronRight,
  Search,
  Bell,
  Plus,
  Upload,
  FileText,
  BookOpen,
  Scale,
  ScrollText,
  Workflow as WorkflowIcon,
  ShieldCheck,
  X,
  Copy,
  Check,
  ArrowRight,
  ArrowDown,
  ExternalLink,
  Info,
  AlertTriangle,
  CircleAlert,
  Inbox,
  Sparkles,
  GitCompareArrows,
  Play,
  RefreshCw,
  ChevronDown,
  Filter,
  Trash2,
} from "lucide-react";
